<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <ApplicationIcon />
    <StartupObject />
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>MapEditor</AssemblyName>
    <RootNamespace>MapEditor</RootNamespace>
    <Copyright>Antonín Pražský</Copyright>
    <PackageIcon>Icon.ico</PackageIcon>
    <PackageIconUrl />
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>TRACE;RELEASE</DefineConstants>
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <MonoGameContentReference Include="**\*.mgcb" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Content\bin\**" />
    <Compile Remove="Content\obj\**" />
    <EmbeddedResource Remove="Content\bin\**" />
    <EmbeddedResource Remove="Content\obj\**" />
    <MonoGameContentReference Remove="Content\bin\**" />
    <MonoGameContentReference Remove="Content\obj\**" />
    <None Remove="Content\bin\**" />
    <None Remove="Content\obj\**" />
    <None Include="Icon.ico">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL.Core" Version="3.7.0.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BS3DLibs\Prazsky.BS3D\Prazsky.BS3D.csproj" />
    <ProjectReference Include="..\BS3DLibs\Prazsky.Core\Prazsky.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="MonoGame.Framework">
      <HintPath>C:\Program Files (x86)\MonoGame\v3.0\Assemblies\Windows\MonoGame.Framework.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
