<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
    <StartupObject>MapEditor.Program</StartupObject>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>MapEditor</AssemblyName>
    <RootNamespace>MapEditor</RootNamespace>
    <Copyright>Antonín Pražský</Copyright>
    <PackageIcon>Icon.ico</PackageIcon>
    <PackageIconUrl />
    <UseWindowsForms>True</UseWindowsForms>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>TRACE;RELEASE</DefineConstants>
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <MonoGameContentReference Include="**\*.mgcb" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Content\bin\**" />
    <Compile Remove="Content\obj\**" />
    <EmbeddedResource Remove="Content\bin\**" />
    <EmbeddedResource Remove="Content\obj\**" />
    <MonoGameContentReference Remove="Content\bin\**" />
    <MonoGameContentReference Remove="Content\obj\**" />
    <None Remove="Content\bin\**" />
    <None Remove="Content\obj\**" />
    <Content Include="Icon.ico" />
    <None Include="Icon.ico">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Content.Builder.BadEchoTask" Version="3.8.2.1-develop" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BS3DLibs\Prazsky.BS3D\Prazsky.BS3D.csproj" />
    <ProjectReference Include="..\BS3DLibs\Prazsky.Core\Prazsky.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Content\Fonts\cascadia.spritefont">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
