<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Prazsky.BS3D\Prazsky.BS3D.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BepuPhysics">
      <HintPath>..\..\..\..\..\..\..\GitHub\bepuphysics2\BepuPhysics\bin\Release\net7.0\BepuPhysics.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
