<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <Authors></Authors>
    <Description></Description>
    <PackageTags>monogame input event based listeners</PackageTags>
    <PackageProjectUrl></PackageProjectUrl>
    <RepositoryUrl></RepositoryUrl>
    <PackageIconUrl></PackageIconUrl>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>NU1701</NoWarn>
    <AssemblyName>Prazsky.Core</AssemblyName>
    <RootNamespace>Prazsky.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />
    <PackageReference Include="MonoGame.Framework.DesktopGL.Core" Version="3.8.0.2" />
  </ItemGroup>
</Project>